import { Amount, FullSignature, PubkeyBundle, SignedTransaction, UnsignedTransaction } from "@iov/bcp";
import * as codecImpl from "./generated/codecimpl";
import { Participant, PrivateKeyBundle } from "./types";
export declare function encodePubkey(publicKey: PubkeyBundle): codecImpl.crypto.IPublicKey;
export declare function encodePrivkey(privateKey: PrivateKeyBundle): codecImpl.crypto.IPrivateKey;
export declare function encodeAmount(amount: Amount): codecImpl.coin.ICoin;
export declare function encodeFullSignature(fullSignature: FullSignature): codecImpl.sigs.IStdSignature;
export declare function encodeParticipants(participants: readonly Participant[]): codecImpl.multisig.IParticipant[];
export declare function buildMsg(tx: UnsignedTransaction): codecImpl.app.ITx;
export declare function buildUnsignedTx(tx: UnsignedTransaction): codecImpl.app.ITx;
export declare function buildSignedTx(tx: SignedTransaction): codecImpl.app.ITx;
