import { Address, Amount, FullSignature, SendTx, SignedTransaction } from "@iov/bcp-types";
import { ChainId, PublicKeyBundle, PublicKeyBytes } from "@iov/tendermint-types";
import { PrivateKeyBundle } from "./types";
export declare const pubJson: PublicKeyBundle;
export declare const pubBin: Uint8Array;
export declare const privJson: PrivateKeyBundle;
export declare const privBin: Uint8Array;
export declare const address: Address;
export declare const coinJson: Amount;
export declare const coinBin: Uint8Array;
export declare const chainId: ChainId;
export declare const sendTxJson: SendTx;
export declare const sendTxBin: Uint8Array;
export declare const signBytes: Uint8Array;
export declare const sig: FullSignature;
export declare const signedTxJson: SignedTransaction;
export declare const signedTxBin: Uint8Array;
export declare const randomTxJson: SignedTransaction;
export declare const setNameTxJson: SignedTransaction;
export declare const hashCode: Uint8Array;
export declare const swapCounterTxJson: SignedTransaction;
export declare const swapClaimTxJson: SignedTransaction;
export declare const swapTimeoutTxJson: SignedTransaction;
export declare const registerBlockchainTransaction: {
    ownerEd25519Pubkey: PublicKeyBytes;
    ownerAddredd: Uint8Array;
    blockchainId: ChainId;
    expectedBinary: Uint8Array;
};
