import { As } from "type-tagger";
import { Address, Nonce, SignableBytes } from "@iov/bcp-types";
import { ChainId, PublicKeyBundle } from "@iov/tendermint-types";
export declare const keyToAddress: (key: PublicKeyBundle) => Address;
export declare const keyToIdentifier: (key: PublicKeyBundle) => Uint8Array;
export declare const appendSignBytes: (bz: Uint8Array, chainId: ChainId, nonce: Nonce) => SignableBytes;
export declare const tendermintHash: (data: Uint8Array) => Uint8Array;
export declare const arraysEqual: (a: Uint8Array, b: Uint8Array) => boolean;
export declare type HashId = Uint8Array & As<"hashid">;
export declare const hashId: Uint8Array;
export declare const preimageIdentifier: (data: Uint8Array) => HashId;
export declare const hashIdentifier: (hash: Uint8Array) => HashId;
export declare const isHashIdentifier: (ident: Uint8Array) => ident is HashId;
export declare const hashFromIdentifier: (ident: HashId) => Uint8Array;
