import { Address } from "@iov/bcp-types";
import { Ed25519Keypair } from "@iov/crypto";
/**
 * Lisk-specific passphrase to Ed25519 keypair derivation
 *
 * "passphrase" is Lisk's word for an autogenerated 12 word english BIP39 mnemonic
 * encoded as a string. Since the BIP39 property is not used for anything but validation
 * in the user interface we work with plain strings here.
 */
export declare function passphraseToKeypair(passphrase: string): Promise<Ed25519Keypair>;
export declare function pubkeyToAddress(pubkey: Uint8Array): Address;
export declare function isValidAddress(address: string): boolean;
export declare function isValidAddressWithEnding(address: string, ending: string): boolean;
