import { PrehashType, SignableBytes } from "@iov/bcp-types";
import { KeyringEntry, KeyringEntryImplementationIdString, KeyringEntrySerializationString, LocalIdentity, PublicIdentity, ValueAndUpdates } from "@iov/keycontrol";
import { ChainId, SignatureBytes } from "@iov/tendermint-types";
import { LedgerState } from "./statetracker";
export declare class LedgerSimpleAddressKeyringEntry implements KeyringEntry {
    static readonly implementationId: KeyringEntryImplementationIdString;
    static registerWithKeyring(): void;
    private static identityId;
    readonly label: ValueAndUpdates<string | undefined>;
    readonly canSign: ValueAndUpdates<boolean>;
    readonly implementationId: KeyringEntryImplementationIdString;
    readonly deviceState: ValueAndUpdates<LedgerState>;
    id: string;
    private readonly deviceTracker;
    private readonly labelProducer;
    private readonly canSignProducer;
    private readonly identities;
    private readonly simpleAddressIndices;
    constructor(data?: KeyringEntrySerializationString);
    startDeviceTracking(): void;
    stopDeviceTracking(): void;
    setLabel(label: string | undefined): void;
    createIdentity(): Promise<LocalIdentity>;
    setIdentityLabel(identity: PublicIdentity, label: string | undefined): void;
    getIdentities(): ReadonlyArray<LocalIdentity>;
    createTransactionSignature(identity: PublicIdentity, transactionBytes: SignableBytes, prehashType: PrehashType, _: ChainId): Promise<SignatureBytes>;
    serialize(): KeyringEntrySerializationString;
    clone(): KeyringEntry;
    private simpleAddressIndex;
    private buildLocalIdentity;
}
